version: 2
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: pull
          command: git pull origin master

workflows:
  version: 2
  release:
    jobs:
    - deploy:
        filters:
          branches:
            only: master