version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh admin_ftp_11@vps-1049136-17732.host4g.ru 'cd ~/mishka && git pull origin master'

workflows:
  version: 2
  release:
    jobs:
    - deploy:
        filters:
          branches:
            only: master